gravatar_forSize : 80
validateMail : 50
validateName : 255
validatePassword : 6
m : "1"
gravatar_forSize2 : 50
per_page : 8
host : "<your heroku app>.herokuapp.com"
address : "smtp.sendgrid.net"
port : "587"
username : "SENDGRID_USERNAME"
password : "SENDGRID_PASSWORD"
domain : "heroku.com"
microPostSize : 50
lim : "should be less than 5MB"
contentMaximum : 140
pMax : 5
acceptFile : "image/jpeg,image/gif,image/png"
